spring.application.name=smartqueue-backend
server.port=8080
spring.data.mongodb.uri=mongodb+srv://sagar1908:sagar190805@cluster0.juxkvw7.mongodb.net/UserDb
spring.data.mongodb.database=UserDb
jwt.secret=SmartQueueSecretKey2024MustBeLongEnoughForHS256Algorithm!!
jwt.expiration=86400000
logging.level.com.smartqueue=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.data.mongodb=WARN
spring.devtools.restart.enabled=true
